import { EC2Instance } from "../interfaces/instance";

export const testInstanceList: Array<EC2Instance> = [
  {
    instanceName: "name0",
    instanceId: "id0",
    imageId: "image0",
    instanceType: "type0",
    instanceStateName: "state0",
    monitoringState: "monitoring0",
  },
  {
    instanceName: "name1",
    instanceId: "id1",
    imageId: "image1",
    instanceType: "type1",
    instanceStateName: "state1",
    monitoringState: "monitoring1",
  },
  {
    instanceName: "name2",
    instanceId: "id2",
    imageId: "image2",
    instanceType: "type2",
    instanceStateName: "state2",
    monitoringState: "monitoring2",
  },
  {
    instanceName: "name3",
    instanceId: "id3",
    imageId: "image3",
    instanceType: "type3",
    instanceStateName: "state3",
    monitoringState: "monitoring3",
  },
  {
    instanceName: "name4",
    instanceId: "id4",
    imageId: "image4",
    instanceType: "type4",
    instanceStateName: "state4",
    monitoringState: "monitoring4",
  },
  {
    instanceName: "name5",
    instanceId: "id5",
    imageId: "image5",
    instanceType: "type5",
    instanceStateName: "state5",
    monitoringState: "monitoring5",
  },
  {
    instanceName: "name6",
    instanceId: "id6",
    imageId: "image6",
    instanceType: "type6",
    instanceStateName: "state6",
    monitoringState: "monitoring6",
  },
  {
    instanceName: "name7",
    instanceId: "id7",
    imageId: "image7",
    instanceType: "type7",
    instanceStateName: "state7",
    monitoringState: "monitoring7",
  },
  {
    instanceName: "name8",
    instanceId: "id6",
    imageId: "image6",
    instanceType: "type6",
    instanceStateName: "state6",
    monitoringState: "monitoring6",
  },
  {
    instanceName: "name9",
    instanceId: "id7",
    imageId: "image7",
    instanceType: "type7",
    instanceStateName: "state7",
    monitoringState: "monitoring7",
  },
  {
    instanceName: "name10",
    instanceId: "id10",
    imageId: "image10",
    instanceType: "type10",
    instanceStateName: "state10",
    monitoringState: "monitoring10",
  },
  {
    instanceName: "name11",
    instanceId: "id11",
    imageId: "image11",
    instanceType: "type11",
    instanceStateName: "state11",
    monitoringState: "monitoring11",
  },
  {
    instanceName: "name12",
    instanceId: "id12",
    imageId: "image12",
    instanceType: "type12",
    instanceStateName: "state12",
    monitoringState: "monitoring12",
  },
  {
    instanceName: "name13",
    instanceId: "id13",
    imageId: "image13",
    instanceType: "type13",
    instanceStateName: "state13",
    monitoringState: "monitoring13",
  },
  {
    instanceName: "name14",
    instanceId: "id14",
    imageId: "image14",
    instanceType: "type14",
    instanceStateName: "state14",
    monitoringState: "monitoring14",
  },
  {
    instanceName: "name15",
    instanceId: "id15",
    imageId: "image15",
    instanceType: "type15",
    instanceStateName: "state15",
    monitoringState: "monitoring15",
  },
  {
    instanceName: "name16",
    instanceId: "id16",
    imageId: "image16",
    instanceType: "type16",
    instanceStateName: "state16",
    monitoringState: "monitoring16",
  },
  {
    instanceName: "name17",
    instanceId: "id17",
    imageId: "image17",
    instanceType: "type17",
    instanceStateName: "state17",
    monitoringState: "monitoring17",
  },
  {
    instanceName: "name18",
    instanceId: "id18",
    imageId: "image18",
    instanceType: "type18",
    instanceStateName: "state18",
    monitoringState: "monitoring18",
  },
  {
    instanceName: "name19",
    instanceId: "id19",
    imageId: "image19",
    instanceType: "type19",
    instanceStateName: "state19",
    monitoringState: "monitoring19",
  },
  {
    instanceName: "nam20",
    instanceId: "id0",
    imageId: "image0",
    instanceType: "type0",
    instanceStateName: "state0",
    monitoringState: "monitoring0",
  },
  {
    instanceName: "nam21",
    instanceId: "id1",
    imageId: "image1",
    instanceType: "type1",
    instanceStateName: "state1",
    monitoringState: "monitoring1",
  },
  {
    instanceName: "nam22",
    instanceId: "id2",
    imageId: "image2",
    instanceType: "type2",
    instanceStateName: "state2",
    monitoringState: "monitoring2",
  },
  {
    instanceName: "nam23",
    instanceId: "id3",
    imageId: "image3",
    instanceType: "type3",
    instanceStateName: "state3",
    monitoringState: "monitoring3",
  },
  {
    instanceName: "nam24",
    instanceId: "id4",
    imageId: "image4",
    instanceType: "type4",
    instanceStateName: "state4",
    monitoringState: "monitoring4",
  },
  {
    instanceName: "nam25",
    instanceId: "id5",
    imageId: "image5",
    instanceType: "type5",
    instanceStateName: "state5",
    monitoringState: "monitoring5",
  },
  {
    instanceName: "nam26",
    instanceId: "id6",
    imageId: "image6",
    instanceType: "type6",
    instanceStateName: "state6",
    monitoringState: "monitoring6",
  },
  {
    instanceName: "nam27",
    instanceId: "id7",
    imageId: "image7",
    instanceType: "type7",
    instanceStateName: "state7",
    monitoringState: "monitoring7",
  },
  {
    instanceName: "nam28",
    instanceId: "id6",
    imageId: "image6",
    instanceType: "type6",
    instanceStateName: "state6",
    monitoringState: "monitoring6",
  },
  {
    instanceName: "nam29",
    instanceId: "id7",
    imageId: "image7",
    instanceType: "type7",
    instanceStateName: "state7",
    monitoringState: "monitoring7",
  },
  {
    instanceName: "name20",
    instanceId: "id10",
    imageId: "image10",
    instanceType: "type10",
    instanceStateName: "state10",
    monitoringState: "monitoring10",
  },
  {
    instanceName: "name21",
    instanceId: "id11",
    imageId: "image11",
    instanceType: "type11",
    instanceStateName: "state11",
    monitoringState: "monitoring11",
  },
  {
    instanceName: "name22",
    instanceId: "id12",
    imageId: "image12",
    instanceType: "type12",
    instanceStateName: "state12",
    monitoringState: "monitoring12",
  },
  {
    instanceName: "name23",
    instanceId: "id13",
    imageId: "image13",
    instanceType: "type13",
    instanceStateName: "state13",
    monitoringState: "monitoring13",
  },
  {
    instanceName: "name24",
    instanceId: "id14",
    imageId: "image14",
    instanceType: "type14",
    instanceStateName: "state14",
    monitoringState: "monitoring14",
  },
  {
    instanceName: "name25",
    instanceId: "id15",
    imageId: "image15",
    instanceType: "type15",
    instanceStateName: "state15",
    monitoringState: "monitoring15",
  },
  {
    instanceName: "name26",
    instanceId: "id16",
    imageId: "image16",
    instanceType: "type16",
    instanceStateName: "state16",
    monitoringState: "monitoring16",
  },
  {
    instanceName: "name27",
    instanceId: "id17",
    imageId: "image17",
    instanceType: "type17",
    instanceStateName: "state17",
    monitoringState: "monitoring17",
  },
  {
    instanceName: "name28",
    instanceId: "id18",
    imageId: "image18",
    instanceType: "type18",
    instanceStateName: "state18",
    monitoringState: "monitoring18",
  },
  {
    instanceName: "name29",
    instanceId: "id19",
    imageId: "image19",
    instanceType: "type19",
    instanceStateName: "state19",
    monitoringState: "monitoring19",
  },
];
